Adx 458 update tests
fjelltopp/ckanext-ytp-request pull request #14
Opened 2020-10-29 12:09 UTC by jsoppela

2020-10-30 13:10 UTC, jonathansberry requested changes
We've worked together on this so I know it's good stuff.  Just spotted a typo - we're commenting out a line rather than removing it.

2020-10-30 13:10 UTC, jonathansberry commented on ckanext/ytp/request/tests/test_plugin.py
> +#webtest_submit = helpers.webtest_submit
Guessing this is a typo... Let's remove rather than comment out.

2020-10-30 15:49 UTC, Manoj-nathwani requested changes

2020-10-30 15:49 UTC, Manoj-nathwani commented on ckanext/ytp/request/logic/action/update.py
> +from sqlalchemy import asc, desc
```suggestion
from sqlalchemy import desc
```

2020-10-30 15:49 UTC, Manoj-nathwani commented on ckanext/ytp/request/logic/action/get.py
> +from sqlalchemy import asc, desc
```suggestion
from sqlalchemy import desc
```

2020-10-30 15:49 UTC, Manoj-nathwani commented on ckanext/ytp/request/logic/action/delete.py
> +from sqlalchemy import asc, desc
```suggestion
from sqlalchemy import desc
```

- I see why you've aded `asc` here
- Buuuuut travis will fail as you're importing something which is never used
- You'll need to remove it to make travis happy

2020-10-30 15:52 UTC, Manoj-nathwani commented
Looks great, I've just removed the unused imports to stop travis being unhappy with pep8 validation checks. I remember it being suuuper strict 😅

2020-11-02 12:57 UTC, jonathansberry commented
As we are migrating away from travis, and I have confirmed that these changes make the tests pass locally, I will merge and close this PR.

2020-11-02 12:57 UTC, merged